// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindTaskById(ctx context.Context, id pgtype.UUID) (Task, error)
	ListTasks(ctx context.Context) ([]Task, error)
}

var _ Querier = (*Queries)(nil)
